version: '3.1'

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - /var/lib/test/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 55432:5432
  python:
    build: ./docker/
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app/
      - /var/logs/results/:/var/logs/results/
      - /var/log/:/var/log/
    command: python monitor.py
  # cron:
  #   depends_on:
  #     - python
