version: '3.1'

services:

  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - /var/lib/test/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 55432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
  python:
    build: ./docker/
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app/